### ISSUE TITLE
COM4J throws exception - VB.Net DLL

### ISSUE THREAD

**Issue by grahamengland** [kohsuke/com4j#59]
I have a common library of about 150 functions created in VB.Net (compiled COM DLL) which I'm trying to open up to Java using com4J, but when I submit the command line entry (java -cp . -jar tlbimp.jar -o DLL2JAR -p CommonDLL c:\factory\graham_net\Graham_Net.dll) I get the following exception error…
Exception in thread "main" com4j.ExecutionException: com4j.ComException: 80029c4
a LoadTypeLib failed : Error loading type library/DLL. : .\com4j.cpp:398
        at com4j.ComThread.execute(ComThread.java:203)
        at com4j.Task.execute(Task.java:25)
        at com4j.COM4J.loadTypeLibrary(COM4J.java:322)
        at com4j.tlbimp.driver.Lib.getLibid(Lib.java:90)
        at com4j.tlbimp.driver.Driver.addLib(Driver.java:38)
        at com4j.tlbimp.driver.Main.doMain(Main.java:123)
        at com4j.tlbimp.driver.Main.main(Main.java:56)
Caused by: com4j.ComException: 80029c4a LoadTypeLib failed : Error loading type
library/DLL. : .\com4j.cpp:398
        at com4j.Native.loadTypeLibrary(Native Method)
        at com4j.COM4J$2.call(COM4J.java:324)
        at com4j.COM4J$2.call(COM4J.java:322)
        at com4j.Task.invoke(Task.java:51)
        at com4j.ComThread.run0(ComThread.java:153)
        at com4j.ComThread.run(ComThread.java:134)

**Comment by johnson-yeap** [comment]
@grahamengland Did you find the solution?

**Comment by grahamengland** [comment]
@johnson-yeap - No, so I decided to convert my VB.Net code to Java instead.  I'm using a great tool to help in this process - the "VB to Java Converter" from Tangible...
https://www.tangiblesoftwaresolutions.com/product_details/vb_to_java_converter_details.html
